### ISSUE TITLE
The semantics of tail()

### ISSUE THREAD

**Issue by akoebbe** [ericpoe/haystack#1]
Great job on this project. This is a big need in the PHP world.

I'm having a bit of a hard time agreeing that the tail() method is named properly. On at first glance I expected tail to give me the last element of a collection and not everything but the head. I equated it to the unix tail command which (by default) gives you the last 10 lines of a file. Is there a precedent in other languages for a tail() method to do as this project does now?

**Comment by ericpoe** [comment]
Hi Andrew, thanks for checking out ophp and thank you for asking about the semantics of my decision to call his method "tail()." There is precedent for tail to be everything in the list that isn't the head: Haskell's [tail()](https://hackage.haskell.org/package/base-4.8.1.0/docs/Data-List.html#v:tail) function is what I based this on.
