### ISSUE TITLE
Lower PHP version constraint to >= 5.5.9

### ISSUE THREAD

**Issue by johnkary** [ericpoe/haystack#10]
Drupal 8 has a [minimum requirement](https://www.drupal.org/requirements) of PHP >= 5.5.9. Drupal developers may be unable to use Haystack if their host only provides the minimum PHP version. Given Drupal's wide appeal could we consider lowering Haystack's minimum requirements to PHP 5.5.9+?

Moving from PHP 5.4 to 5.6 started here: https://github.com/ericpoe/haystack/commit/4a62a0dd2eab38f8e8e835e9df997d8ebf19f141

**Comment by ericpoe** [comment]
Excellent use case!
